{{- range $kstfs, $sts := $.Values.statefulset }}
{{- with $sts.horizontalPodAutoscaler }}
{{- if and .enabled $sts.replicas }}

{{fail "VALIDATION FILED: Specify eaither replicas, or horizontalPodAutoscaler!!!"}}
{{- end -}}
{{- if .enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{$kstfs}}
  labels:
    {{- include "universal-helm.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $kstfs }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- if .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .targetMemoryUtilizationPercentage }}
          type: Utilization
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
