{{- $global := .Values.global | default dict }}
{{- $serviceAccount := $global.serviceAccount | default dict }}
{{- if $serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  labels:
    {{- include "universal-helm.labels" . | nindent 4 }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}