{{- range $kstfs, $sts := $.Values.statefulset }}
{{- range $kcntnr, $cntnr := $sts.containers }}
{{- range $kprt, $prt := $cntnr.ports }}

{{- if $prt.service }}
{{- if or $prt.service.enabled (not (has $prt.service .enabled)) }}{{/* # If enabled==true or not given*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$kstfs}}-{{ $prt.name }}
  labels:
    {{- include "universal-helm.labels" $ | nindent 4 }}

  {{ with $sts.service.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  selector:
    statefulsetname: {{ $kstfs }}
  type: {{ $prt.service.type }}
  ports:
    - port: {{ $prt.port }}
      targetPort: {{ $prt.port }}
      protocol: {{ $prt.protocol }}
      name: {{ $prt.name }}

{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
